import type { Locale } from "./i18n.ts";

const es = {
  home: "Inicio",
  production: "Producción",
  routes: "Rutas",
  diary: "Diario",
  more: "Más",
  nav: "Secciones",
  sources: "Fuentes",
  skip: "Ir al contenido",
  connect: "Conectar partida",
  install: "Instalación y lecturas",
  board: "Tablero",
  map: "Mapa",
  catalog: "Catálogo",
  companion: "Tu compañero en Anno 1800",
  kicker: "PARTE DEL PUERTO",
  title: "Tu puerto, en un vistazo.",
  intro: "Qué revisar, por qué importa y qué podés hacer después.",
  save: "Guardado",
  ocr: "OCR",
  island: "Isla OCR",
  focusIsland: "Isla: {0}",
  unknownTime: "sin fecha de observación",
  noRead: "sin lectura",
  noIsland: "isla sin identificar",
  imported: "Última lectura importada",
  watching: "Leyendo el archivo elegido",
  stopped: "Sin lectura actual · revisá la conexión",
  refresh: "Actualizar lectura",
  manual: "Importación manual",
  refreshFailed: "No pude leer el archivo. Reconectalo desde Conectar partida.",
  first: "TU SIGUIENTE PRIORIDAD",
  also: "OTRA COSA PARA REVISAR",
  productionKicker: "PARA DECIDIR SOBRE PRODUCCIÓN",
  evidence: "Ver evidencia",
  viewRoute: "Ver ruta",
  viewProduction: "Ver producción",
  viewTreasury: "Ver la caja",
  viewFleet: "Ver la flota",
  treasuryTitle: "Las monedas bajan en varios guardados.",
  treasuryBody: "No parece una sola compra. Revisá la caja en Taller.",
  essentialTitle: "{0}: baja en más de un guardado.",
  essentialLimit: "Investigación. No demuestra que una ruta lo haya causado.",
  confirmed: "Confirmado en guardado",
  observed: "Observado",
  inferred: "Inferido",
  global: "Stock global",
  finance: "Finanzas",
  historical: "Última observación · no es estado actual",
  ship: "La ruta no tiene barco asignado.",
  stops: "La ruta tiene menos de dos paradas.",
  goods: "La ruta no tiene bienes configurados.",
  routeTitle: "Revisá {0}",
  stockTitle: "{0}: el stock global bajó.",
  stockLimit: "Entre guardados. No demuestra un fallo de la ruta.",
  missing: "{0}: revisá la capacidad.",
  surplus: "{0}: podría sobrar capacidad.",
  productionNumbers: "Capacidad calculada: {0} t/min · demanda leída: {1} t/min.",
  productionLimit: "Estimación de esta isla; revisá el detalle antes de construir o pausar.",
  emptyTitle: "Tu partida, cuando quieras.",
  emptyBody:
    "Conectá harbor-live.json para revisar producción y rutas. También podés seguir la campaña sin conectar nada.",
  clearTitle: "Sin problemas detectados en las lecturas disponibles.",
  clearBody:
    "Esto no confirma que toda la economía esté equilibrada. Las conclusiones dependen del alcance y la fecha de cada lectura.",
  missingRoutes: "Todavía no hay información de rutas en esta lectura.",
  off: "Producción real, todavía no.",
  offBody:
    "El OCR opcional lee Estadísticas en Anno. No accede a la memoria del juego ni observa todas tus islas.",
  historicalTitle: "Actualizá la lectura de producción.",
  historicalBody:
    "Conservamos la evidencia anterior. Abrí Producción y Finanzas de la misma isla para revisar sus cifras; si no llegan lecturas, revisá la instalación.",
  productionTitle: "Falta leer Producción.",
  productionBody:
    "Abrí Estadísticas → Producción de la isla que querés revisar y dejala visible unos segundos.",
  financeTitle: "Falta una lectura vigente de Finanzas.",
  financeBody: "Abrí Estadísticas → Finanzas de la misma isla para contar las fábricas.",
  catalogTitle: "La lectura necesita más contexto.",
  catalogBody:
    "No hay un cálculo seguro para estos edificios en el catálogo actual. No vamos a adivinar sus ritmos.",
  readyTitle: "Producción con evidencia disponible.",
  readyBody: "Podés revisar demanda, capacidad calculada y fábricas de la isla leída en el Taller.",
  diaryKicker: "TU CAMPAÑA SIGUE ACÁ",
  diaryTitle: "El mismo mundo, más claro.",
  diaryBody: "Tus misiones, planos y próximos pasos siguen en el Diario. Conservamos tu progreso.",
  openDiary: "Abrir Diario",
  footer: "Lectura local. Tu partida no se modifica. Proyecto fan no oficial; no afiliado a Ubisoft.",
  scope: "Cada conclusión tiene un alcance",
  scopeBody:
    "Guardados: configuración de rutas y cambios de stock global. OCR: muestras de la pantalla y la isla visibles en Anno.",
  demo: "Demostración · datos ilustrativos",
};
type Copy = { [K in keyof typeof es]: string };
const en: Copy = {
  home: "Home",
  production: "Production",
  routes: "Routes",
  diary: "Journal",
  more: "More",
  nav: "Sections",
  sources: "Sources",
  skip: "Skip to content",
  connect: "Connect game",
  install: "Setup and readings",
  board: "Board",
  map: "Map",
  catalog: "Catalog",
  companion: "Your Anno 1800 companion",
  kicker: "HARBOR DISPATCH",
  title: "Your harbor, at a glance.",
  intro: "What to review, why it matters, and what to do next.",
  save: "Save",
  ocr: "OCR",
  island: "OCR island",
  focusIsland: "Island: {0}",
  unknownTime: "observation date unavailable",
  noRead: "no reading",
  noIsland: "unidentified island",
  imported: "Last imported reading",
  watching: "Reading the selected file",
  stopped: "No current reading · check connection",
  refresh: "Refresh reading",
  manual: "Manual import",
  refreshFailed: "Could not read the file. Reconnect it from Connect game.",
  first: "YOUR NEXT PRIORITY",
  also: "ALSO WORTH REVIEWING",
  productionKicker: "TO DECIDE ABOUT PRODUCTION",
  evidence: "View evidence",
  viewRoute: "View route",
  viewProduction: "View production",
  viewTreasury: "Review the cash",
  viewFleet: "View the fleet",
  treasuryTitle: "Coins fall across several saves.",
  treasuryBody: "This does not look like a single purchase. Review the cash in Workshop.",
  essentialTitle: "{0}: falling across more than one save.",
  essentialLimit: "Something to investigate. This does not prove a route caused it.",
  confirmed: "Confirmed in save",
  observed: "Observed",
  inferred: "Inferred",
  global: "Global stock",
  finance: "Finance",
  historical: "Last observation · not current state",
  ship: "The route has no assigned ship.",
  stops: "The route has fewer than two stops.",
  goods: "The route has no configured goods.",
  routeTitle: "Review {0}",
  stockTitle: "{0}: global stock fell.",
  stockLimit: "Between saves. This does not prove a route failure.",
  missing: "{0}: review capacity.",
  surplus: "{0}: possible excess capacity.",
  productionNumbers: "Calculated capacity: {0} t/min · observed demand: {1} t/min.",
  productionLimit: "Island-specific estimate; review details before building or pausing.",
  emptyTitle: "Your game, when you are ready.",
  emptyBody:
    "Connect harbor-live.json to review production and routes. You can also continue the campaign without connecting anything.",
  clearTitle: "No issues detected in the available readings.",
  clearBody:
    "This does not confirm that the entire economy is balanced. Conclusions depend on the scope and age of each reading.",
  missingRoutes: "This reading does not contain route information yet.",
  off: "Real production, not yet.",
  offBody:
    "Optional OCR reads Anno's Statistics screens. It does not access game memory or observe all your islands.",
  historicalTitle: "Refresh the production reading.",
  historicalBody:
    "Previous evidence is retained. Open Production and Finance for the same island to refresh the figures; check setup if readings do not arrive.",
  productionTitle: "A Production reading is missing.",
  productionBody:
    "Open Statistics → Production for the island you want to review and leave it visible for a few seconds.",
  financeTitle: "A recent Finance reading is missing.",
  financeBody: "Open Statistics → Finance for the same island to count factories.",
  catalogTitle: "This reading needs more context.",
  catalogBody:
    "The current catalog cannot safely calculate these buildings. We will not guess their rates.",
  readyTitle: "Production evidence is available.",
  readyBody:
    "Review demand, calculated capacity and factories for the observed island in the Workshop.",
  diaryKicker: "YOUR CAMPAIGN CONTINUES HERE",
  diaryTitle: "The same world, a clearer view.",
  diaryBody:
    "Your missions, layouts and next steps remain in the Journal. Your progress is preserved.",
  openDiary: "Open Journal",
  footer: "Local reading. Your save is never modified. Unofficial fan project; not affiliated with Ubisoft.",
  scope: "Every conclusion has a scope",
  scopeBody:
    "Saves: route configuration and global stock changes. OCR: samples of the screen and island visible in Anno.",
  demo: "Demonstration · illustrative data",
};
const it: Copy = {
  home: "Inizio",
  production: "Produzione",
  routes: "Rotte",
  diary: "Diario",
  more: "Altro",
  nav: "Sezioni",
  sources: "Fonti",
  skip: "Vai al contenuto",
  connect: "Collega partita",
  install: "Installazione e letture",
  board: "Quadro",
  map: "Mappa",
  catalog: "Catalogo",
  companion: "Il tuo compagno in Anno 1800",
  kicker: "BOLLETTINO DEL PORTO",
  title: "Il tuo porto, a colpo d’occhio.",
  intro: "Cosa controllare, perché conta e cosa fare dopo.",
  save: "Salvataggio",
  ocr: "OCR",
  island: "Isola OCR",
  focusIsland: "Isola: {0}",
  unknownTime: "data di osservazione assente",
  noRead: "nessuna lettura",
  noIsland: "isola non identificata",
  imported: "Ultima lettura importata",
  watching: "Lettura del file selezionato",
  stopped: "Nessuna lettura attuale · controlla la connessione",
  refresh: "Aggiorna lettura",
  manual: "Importazione manuale",
  refreshFailed: "Impossibile leggere il file. Ricollegalo da Collega partita.",
  first: "LA PROSSIMA PRIORITÀ",
  also: "DA CONTROLLARE ANCHE",
  productionKicker: "PER DECIDERE SULLA PRODUZIONE",
  evidence: "Vedi evidenza",
  viewRoute: "Vedi rotta",
  viewProduction: "Vedi produzione",
  viewTreasury: "Vedi la cassa",
  viewFleet: "Vedi la flotta",
  treasuryTitle: "Le monete scendono in più salvataggi.",
  treasuryBody: "Non sembra un solo acquisto. Controlla la cassa nel Laboratorio.",
  essentialTitle: "{0}: scende in più di un salvataggio.",
  essentialLimit: "Da indagare. Non dimostra che una rotta l’abbia causato.",
  confirmed: "Confermato nel salvataggio",
  observed: "Osservato",
  inferred: "Dedotto",
  global: "Scorte globali",
  finance: "Finanze",
  historical: "Ultima osservazione · non è lo stato attuale",
  ship: "La rotta non ha navi assegnate.",
  stops: "La rotta ha meno di due fermate.",
  goods: "La rotta non ha merci configurate.",
  routeTitle: "Controlla {0}",
  stockTitle: "{0}: scorte globali in calo.",
  stockLimit: "Tra salvataggi. Non dimostra un guasto della rotta.",
  missing: "{0}: controlla la capacità.",
  surplus: "{0}: possibile capacità in eccesso.",
  productionNumbers: "Capacità calcolata: {0} t/min · domanda letta: {1} t/min.",
  productionLimit: "Stima per quest’isola; controlla i dettagli prima di costruire o sospendere.",
  emptyTitle: "La tua partita, quando vuoi.",
  emptyBody:
    "Collega harbor-live.json per controllare produzione e rotte. Puoi continuare la campagna anche senza collegare nulla.",
  clearTitle: "Nessun problema rilevato nelle letture disponibili.",
  clearBody:
    "Non conferma che l’intera economia sia equilibrata. Le conclusioni dipendono dall’ambito e dall’età di ogni lettura.",
  missingRoutes: "Questa lettura non contiene ancora informazioni sulle rotte.",
  off: "Produzione reale, non ancora.",
  offBody:
    "L’OCR facoltativo legge le Statistiche di Anno. Non accede alla memoria del gioco e non osserva tutte le isole.",
  historicalTitle: "Aggiorna la lettura della produzione.",
  historicalBody:
    "Le osservazioni precedenti restano disponibili. Apri Produzione e Finanze della stessa isola; controlla l’installazione se le letture non arrivano.",
  productionTitle: "Manca la lettura di Produzione.",
  productionBody:
    "Apri Statistiche → Produzione dell’isola da controllare e lasciala visibile per alcuni secondi.",
  financeTitle: "Manca una lettura recente di Finanze.",
  financeBody: "Apri Statistiche → Finanze della stessa isola per contare le fabbriche.",
  catalogTitle: "La lettura richiede più contesto.",
  catalogBody:
    "Il catalogo attuale non permette un calcolo sicuro per questi edifici. Non inventiamo i ritmi.",
  readyTitle: "Evidenza di produzione disponibile.",
  readyBody:
    "Controlla domanda, capacità calcolata e fabbriche dell’isola osservata nel Laboratorio.",
  diaryKicker: "LA TUA CAMPAGNA CONTINUA QUI",
  diaryTitle: "Lo stesso mondo, più chiaro.",
  diaryBody:
    "Missioni, progetti e prossimi passi restano nel Diario. I tuoi progressi sono conservati.",
  openDiary: "Apri Diario",
  footer: "Lettura locale. La partita non viene modificata. Progetto fan non ufficiale; non affiliato a Ubisoft.",
  scope: "Ogni conclusione ha un ambito",
  scopeBody:
    "Salvataggi: configurazione delle rotte e variazioni delle scorte globali. OCR: campioni della schermata e dell’isola visibili in Anno.",
  demo: "Dimostrazione · dati illustrativi",
};
const de: Copy = {
  home: "Start",
  production: "Produktion",
  routes: "Routen",
  diary: "Journal",
  more: "Mehr",
  nav: "Bereiche",
  sources: "Quellen",
  skip: "Zum Inhalt",
  connect: "Spiel verbinden",
  install: "Einrichtung und Messungen",
  board: "Übersicht",
  map: "Karte",
  catalog: "Katalog",
  companion: "Dein Begleiter für Anno 1800",
  kicker: "HAFENBERICHT",
  title: "Dein Hafen auf einen Blick.",
  intro: "Was du prüfen kannst, warum es wichtig ist und was danach kommt.",
  save: "Spielstand",
  ocr: "OCR",
  island: "OCR-Insel",
  focusIsland: "Insel: {0}",
  unknownTime: "Beobachtungszeit unbekannt",
  noRead: "keine Messung",
  noIsland: "Insel nicht erkannt",
  imported: "Zuletzt importierte Messung",
  watching: "Ausgewählte Datei wird gelesen",
  stopped: "Keine aktuelle Lesung · Verbindung prüfen",
  refresh: "Messung aktualisieren",
  manual: "Manueller Import",
  refreshFailed: "Die Datei konnte nicht gelesen werden. Verbinde sie über Spiel verbinden erneut.",
  first: "DEINE NÄCHSTE PRIORITÄT",
  also: "AUCH EINEN BLICK WERT",
  productionKicker: "ENTSCHEIDUNGEN ZUR PRODUKTION",
  evidence: "Belege ansehen",
  viewRoute: "Route ansehen",
  viewProduction: "Produktion ansehen",
  viewTreasury: "Kasse prüfen",
  viewFleet: "Flotte ansehen",
  treasuryTitle: "Münzen fallen über mehrere Spielstände.",
  treasuryBody: "Das sieht nicht nach einem einzelnen Kauf aus. Prüfe die Kasse in der Werkstatt.",
  essentialTitle: "{0}: fällt über mehr als einen Spielstand.",
  essentialLimit: "Zum Prüfen. Das beweist nicht, dass eine Route es verursacht hat.",
  confirmed: "Im Spielstand bestätigt",
  observed: "Beobachtet",
  inferred: "Abgeleitet",
  global: "Globaler Bestand",
  finance: "Finanzen",
  historical: "Letzte Beobachtung · kein aktueller Zustand",
  ship: "Der Route ist kein Schiff zugewiesen.",
  stops: "Die Route hat weniger als zwei Stopps.",
  goods: "Für die Route sind keine Waren eingestellt.",
  routeTitle: "{0} prüfen",
  stockTitle: "{0}: globaler Bestand gesunken.",
  stockLimit: "Zwischen Spielständen. Dies beweist keinen Routenfehler.",
  missing: "{0}: Kapazität prüfen.",
  surplus: "{0}: möglicherweise überschüssige Kapazität.",
  productionNumbers: "Berechnete Kapazität: {0} t/min · erfasster Bedarf: {1} t/min.",
  productionLimit: "Schätzung für diese Insel; vor dem Bauen oder Pausieren Details prüfen.",
  emptyTitle: "Dein Spiel, sobald du bereit bist.",
  emptyBody:
    "Verbinde harbor-live.json, um Produktion und Routen zu prüfen. Die Kampagne funktioniert auch ohne Verbindung.",
  clearTitle: "Keine Probleme in den verfügbaren Messungen erkannt.",
  clearBody:
    "Das bestätigt kein Gleichgewicht der gesamten Wirtschaft. Aussagen hängen von Umfang und Alter jeder Messung ab.",
  missingRoutes: "Diese Messung enthält noch keine Routeninformationen.",
  off: "Echte Produktionsdaten fehlen noch.",
  offBody:
    "Optionales OCR liest Annos Statistikbildschirme. Es greift nicht auf den Spielspeicher zu und beobachtet nicht alle Inseln.",
  historicalTitle: "Produktionsmessung aktualisieren.",
  historicalBody:
    "Frühere Beobachtungen bleiben erhalten. Öffne Produktion und Finanzen derselben Insel; prüfe die Einrichtung, falls keine Messungen ankommen.",
  productionTitle: "Eine Produktionsmessung fehlt.",
  productionBody:
    "Öffne Statistik → Produktion der gewünschten Insel und lasse sie einige Sekunden sichtbar.",
  financeTitle: "Eine aktuelle Finanzmessung fehlt.",
  financeBody: "Öffne Statistik → Finanzen derselben Insel, um die Fabriken zu zählen.",
  catalogTitle: "Diese Messung braucht mehr Kontext.",
  catalogBody:
    "Der aktuelle Katalog erlaubt keine sichere Berechnung für diese Gebäude. Wir raten keine Produktionsraten.",
  readyTitle: "Produktionsdaten sind verfügbar.",
  readyBody:
    "Prüfe Bedarf, berechnete Kapazität und Fabriken der beobachteten Insel in der Werkstatt.",
  diaryKicker: "DEINE KAMPAGNE GEHT HIER WEITER",
  diaryTitle: "Dieselbe Welt, klarer gesehen.",
  diaryBody:
    "Missionen, Baupläne und nächste Schritte bleiben im Journal. Dein Fortschritt bleibt erhalten.",
  openDiary: "Journal öffnen",
  footer: "Lokales Lesen. Dein Spielstand bleibt unverändert. Inoffizielles Fanprojekt; nicht mit Ubisoft verbunden.",
  scope: "Jede Aussage hat einen Geltungsbereich",
  scopeBody:
    "Spielstände: Routenkonfiguration und globale Bestandsänderungen. OCR: Aufnahmen des in Anno sichtbaren Bildschirms und der Insel.",
  demo: "Demonstration · Beispieldaten",
};
export const editorialCopy: Record<Locale, Copy> = { es, en, it, de };
