/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ConectarRouteImport } from './routes/conectar'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as TableroRouteImport } from './routes/tablero'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectarRoute = ConectarRouteImport.update({
  id: '/conectar',
  path: '/conectar',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const TableroRoute = TableroRouteImport.update({
  id: '/tablero',
  path: '/tablero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/conectar': typeof ConectarRoute
  '/instalar': typeof InstalarRoute
  '/tablero': typeof TableroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/conectar': typeof ConectarRoute
  '/instalar': typeof InstalarRoute
  '/tablero': typeof TableroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/conectar': typeof ConectarRoute
  '/instalar': typeof InstalarRoute
  '/tablero': typeof TableroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogo' | '/conectar' | '/instalar' | '/tablero'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogo' | '/conectar' | '/instalar' | '/tablero'
  id: '__root__' | '/' | '/catalogo' | '/conectar' | '/instalar' | '/tablero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  ConectarRoute: typeof ConectarRoute
  InstalarRoute: typeof InstalarRoute
  TableroRoute: typeof TableroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conectar': {
      id: '/conectar'
      path: '/conectar'
      fullPath: '/conectar'
      preLoaderRoute: typeof ConectarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablero': {
      id: '/tablero'
      path: '/tablero'
      fullPath: '/tablero'
      preLoaderRoute: typeof TableroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  ConectarRoute: ConectarRoute,
  InstalarRoute: InstalarRoute,
  TableroRoute: TableroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
